#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Error: command usage:"
    echo "brancher [ -f | -h | -r | -d ] <branch name>"
fi

case "$1" in
    -f)
        TYPE="FEAT"
        ;;
    -h)
        TYPE="HOTFIX"
        ;;
    -r)
        TYPE="RELEASE"
        ;;
    -d)
        TYPE="DEVELOP"
        ;;
    -*)
        echo "ERROR: flag not recognized"
        ;;
esac

shift

# Si es develop, ignoramos el resto de los argumentos y armamos el nombre directo
if [ "$TYPE" = "develop" ]; then
    FULL_BRANCH_NAME="develop"
else
    # Para los demás flags, seguimos exigiendo el nombre de la rama
    if [ $# -eq 0 ]; then
        echo "Error: Branch name is required"
        exit 1
    fi
    BRANCH="$*"
    FULL_BRANCH_NAME="$TYPE/$BRANCH"
fi

git checkout -b "$FULL_BRANCH_NAME"
git add .
git commit -m "[$TYPE]: branch created"
git push origin "$FULL_BRANCH_NAME" --set-upstream